import "./styles/input.scss";
import "./scripts/themeSwitch.ts";
import "./scripts/humburger.ts";
import "../node_modules/@material-tailwind/html/scripts/toggle.js";
import "../node_modules/@material-tailwind/html/scripts/tabs.js";
import "../node_modules/@material-tailwind/html/scripts/collapse.js";
import "../node_modules/@material-tailwind/html/scripts/dialog.js";
import "../node_modules/@material-tailwind/html/scripts/input.js";
import "../node_modules/@material-tailwind/html/scripts/menu.js"